/** @type {import('tailwindcss').Config} */
// [Layer: Config]
// tailwind.config.cjs -- TailwindCSS v3 configuration with Katipuneros design tokens.
// Extracted 1:1 from the source HTML tailwind.config objects.
// DO NOT change color values -- they match design.md exactly.
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "action-green-hover": "#82D64C",
        "on-error-container": "#93000a",
        "surface-bright": "#f4fbfc",
        "primary-container": "#287ea7",
        "chip-unselected-bg": "rgba(255,255,255,0.70)",
        "surface-tint": "#00658b",
        "text-primary": "#18323D",
        "outline": "#70787f",
        "tertiary-fixed-dim": "#82d1f1",
        "background": "#f4fbfc",
        "action-green": "#9BE564",
        "on-background": "#161d1e",
        "on-surface": "#161d1e",
        "tertiary-fixed": "#baeaff",
        "status-danger": "#B96F72",
        "primary": "#00658a",
        "on-secondary-fixed-variant": "#144c61",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#004d62",
        "tertiary-container": "#26809d",
        "inverse-surface": "#2b3233",
        "text-secondary": "#647982",
        "glass-surface": "rgba(255,255,255,0.55)",
        "surface-container-highest": "#dde4e5",
        "surface-container-high": "#e2e9ea",
        "error": "#ba1a1a",
        "status-pending": "#D9A85C",
        "secondary-container": "#b2e4fe",
        "primary-fixed-dim": "#84cffc",
        "soft-blue": "#D9EEF5",
        "inverse-primary": "#84cffc",
        "secondary": "#31647a",
        "on-primary-container": "#ffffff",
        "on-secondary-fixed": "#001f2a",
        "on-primary-fixed": "#001e2d",
        "secondary-fixed-dim": "#9ccee6",
        "on-tertiary-fixed": "#001f29",
        "on-surface-variant": "#40484e",
        "surface-container": "#e8eff0",
        "surface": "#f4fbfc",
        "surface-container-low": "#eef5f6",
        "on-secondary": "#ffffff",
        "surface-dim": "#d4dbdc",
        "status-available": "#7FA58D",
        "on-primary-fixed-variant": "#004c6a",
        "on-error": "#ffffff",
        "on-secondary-container": "#34677d",
        "on-tertiary-container": "#ffffff",
        "tertiary": "#006681",
        "primary-fixed": "#c5e7ff",
        "surface-variant": "#dde4e5",
        "secondary-fixed": "#bee9ff",
        "outline-variant": "#bfc8cf",
        "inverse-on-surface": "#ebf2f3",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "space-lg": "24px",
        "space-3xl": "64px",
        "space-2xl": "48px",
        "space-xs": "4px",
        "space-md": "16px",
        "space-sm": "8px",
        "space-xl": "32px",
        margin: "32px",
      },
      fontFamily: {
        "body-large": ["Inter"],
        body: ["Inter"],
        small: ["Inter"],
        "display-hero": ["Inter"],
        "display-hero-mobile": ["Inter"],
        "headline-4": ["Inter"],
        "headline-2": ["Inter"],
        caption: ["Inter"],
        "body-medium": ["Inter"],
        "headline-1": ["Inter"],
        "headline-3": ["Inter"],
      },
      fontSize: {
        "body-large": ["18px", { lineHeight: "1.5", fontWeight: "500" }],
        body: ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        small: ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "display-hero": [
          "56px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-hero-mobile": [
          "36px",
          { lineHeight: "1.15", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-4": ["22px", { lineHeight: "1.35", fontWeight: "600" }],
        "headline-2": ["36px", { lineHeight: "1.25", fontWeight: "600" }],
        caption: [
          "12px",
          { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "body-medium": ["16px", { lineHeight: "1.5", fontWeight: "500" }],
        "headline-1": [
          "44px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-3": ["26px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
